// ASSIGNMENT 4 VARIABLE NAMES: LEGAL & ILLEGAL

// Question 1
// var myName = "Jaweria", myCity = "Karachi", favColor = "purple";
// console.log(" NAME :" + myName + " " +"CiTY:"+ myCity+ " " + "Favourite color: " +favColor);
// -------------------------End of Question 1------------------------------

// -------------------------------Question 2---------------------------------
// //Legal words
// var myName;//we can use camel case
// var age;// we can use starting word in lowercase
// var $price;// we can use dollar in the start
// var first_name;//we can use underscore in between
// var my1Book;// we can use number in between

// // Ilegal words
// var 1user; // cannot start with a number
// var user name; // cannot contain space in between between
// var var; // cannot use reserved keywords
// var color-box; // cannot use hyphens
// var #lastName; // cannot use # special character
// -------------------------End of Question 2------------------------------


// // -------------------------------Question 3---------------------------------
// document.write("<h1>Rules for naming JS variables</h1>" +"<br>" +"<br>") ;
// document.write("Variable names can only contain <b>camel case</b>, <b>numbers</b>, <b>dollar($)</b>, and <b>underscores(_)</b>. For example :<b> $my_1stVariable</b>"  +"<br>" )
// document.write("Variables must begin with a <b>lowercase</b>, <b>dollar sign ($)</b>, or <b>underscore (_)</b>. For example <b> $name, _name, or name </b>"  +"<br>" );
// document.write("Variable names are case <b>sensitive</b>"  +"<br>" )
// document.write("Variable names should not be JS <b>Reserved</b> keywords.")


// -------------------------------End of Question 4---------------------------.