// ASSIGNMENT OF QUESTION: 9 & 10

// --------------------------Question 1---------------------------------
// var cityName = prompt("Enter Your City Name");
// if (cityName === "karachi") 
//     alert("Welcome to city of lights");

// else {
//     alert("Welcome");
// }

// -----------------------------End of Question 1-------------------------

// -----------------------------Question 2---------------------------------

// var gender = prompt("Your gender identity");
// if (gender==="male") {
//     alert("Good Morning Sir");
// } 
// else if (gender==="female") {
//     alert("Good Morning Ma’am");
// }
//  else { 
//     alert("Good Morning");
// }

// -----------------------------End of Question 2 -------------------------


// -----------------------------Question 3---------------------------------

// var trafficColor= prompt("Enter The Traffic Color &\n We Will Tell You About the Traffic Rules");

// if (trafficColor==="red"){
//     alert("Must Stop");
// }
// else if (trafficColor==="yellow"){
//    alert("Ready to move");
// }
// else if(trafficColor==="green"){
//     alert("Move now");
// }
// else{
//  alert("This is not a traffic color")
// }

// -----------------------------End of Question 3 -------------------------


// -----------------------------Question 4---------------------------------
//  var fuel= prompt("How Much Litter Fuel Is Remaining in the Car?")
//  if(fuel<0.25){
//     alert("Please refill the fuel in your car")
//  }
//  else{
//     alert("There is enough fuel in the car\n You can drive")
//  }

// -----------------------------End of Question 4 -------------------------

// -----------------------------Question 5---------------------------------
// // Part(a)
// var a = 4;
// if (++a === 5) {
//     alert("given condition for variable a is true");
// }//This condition is true

// // Part(b)
// var b = 82;
// if (b++ === 83) {
//     alert("given condition for variable b is true");
// }////This condition is false

// Part(c)
// var c = 12;
// if (c++ === 13) {
//     alert("condition 1 is true");
// }////This condition is false
// if (c === 13) {
//     alert("condition 2 is true");
// }////This condition is true
// if (++c < 14) {
//     alert("condition 3 is true");
// }//This condition is false
// if (c === 14) {
//     alert("condition 4 is true");
// }//This condition is true

// // Part(d)
// var materialCost = 20000;
// var laborCost = 2000;
// var totalCost = materialCost + laborCost;
// if (totalCost === laborCost + materialCost) {
//     alert("The cost equals");
// }////This condition is true

// // Part(e)
// if (true) {
//     alert("True");
// }
// if(false) {
//     alert("False");
// }//Answer of (e) is true 1st condition is true


// // Part(f)
// if ("car" < "cat") {
//     alert("car is smaller than cat");
//     givenNum + " is divisible by" + 3
// }//This condition is true

// -----------------------------End of Question 5 -------------------------

// -----------------------------Question 6---------------------------------

// document.write("<h1>Mark Sheet</h1>" + "<br>" + "<br>")

// subject_1 = +prompt("Enter marks obtained in subject 1: ")
// subject_2 = +prompt("Enter marks obtained in subject 2: ")
// subject_3 =  +prompt("Enter marks obtained in subject 1: ")
// totalMarks = +prompt("Enter your  total marks: ")

// obtaining_marks = subject_1 + subject_2 + subject_3
// percentage = (obtaining_marks /totalMarks ) * 100

// document.write("Total Marks:"+totalMarks + "<br>" )
// document.write("Marks Obtained:"+obtaining_marks  + "<br>")
// document.write("Percentage:"+ percentage + "% <br>")

// if (percentage >= 80){
//     grade = "A+"
//     remarks = "Excellent"
// }
// else if (percentage >= 70){
//     grade = "A"
//     remarks = "Very Good"
// }
// else if (percentage >= 60){
//     grade = "B"
//     remarks = "Good"
// }
// else if(percentage >= 50){
//     grade = "C"
//     remarks = "Satisfactory"
// }
// else if (percentage >= 40){
//     grade = "D"
//     remarks = "Pass"
// }
// else{
//     grade = "F"
//     remarks = "Fail"
// }

// document.write("Grade:", grade + "<br>")
// document.write("Remarks:", remarks + "<br>")

// -----------------------------End of Question 6 ------------------

// -----------------------------Question 7---------------------------------

// var secretNo =+5;
// var guessNo = +prompt("Guess a secret number between 1 and 10");
// if(guessNo===secretNo){
//     alert("Bingo! Correct answer")
// }
// else if(guessNo===secretNo +1 || guessNo===secretNo -1 ){
//     alert("Close enough to the correct answer")
// }
// else{
//     alert("Your guess is incorrect")
// }

// -----------------------------End of Question 7 ------------------

// -----------------------------Question 8---------------------------------
// var givenNum = prompt("Enter any Number");
// if (givenNum % 3 === 0) {
//     alert(givenNum + " is divisible by " + 3);
// }
// else {
//         alert(givenNum + " is not divisible by " + 3)
//     }

// -----------------------------End of Question 8-------------------------



// -----------------------------Question 9---------------------------------
// var num = prompt("Enter a Number");
// if (num % 2 ===0) {
//     alert(num + " is even" +" number")
// }
// else{
//     alert(num + " is odd" +" number")
//     }

// -----------------------------End of Question 9-------------------------

// -----------------------------Question 10---------------------------------

// var temp = prompt("How much temperature in your city");
// if (temp > 40) {
//     alert("It is too hot outside.");
// }
// else if (temp >30) {
//     alert("The Weather today is Normal.");
// }
// else if (temp >20) {
//     alert("Today’s Weather is cool.");
// }
// else if (temp >10) {
//     alert("OMG! Today’s weather is so Cool.");
// }
// else{
//     alert("invalid temperature")

// }

// -----------------------------End of Question 10-------------------------


// -----------------------------Question 11---------------------------------

// var num1 = +prompt("Enter First  Number");
// var  num2= +prompt("Enter Second  Number");
// var solution = prompt("Select the operation which you want to perform?")

// //Solution
// if(solution==="+"){
// alert(num1 + " + "  +num2 + " = "  + (num1 + num2 ));
// }
// if(solution==="-"){
// alert(num1 + " - "  +num2 + " = "  + (num1 - num2 ));
// }
// if(solution==="*"){
//  alert(num1 +  " * "  +num2 + " = "  + (num1 * num2 ));
//  }
//  if(solution==="/"){
// alert(num1 + " / "  +num2 + " = "  + (num1 / num2 ));
// }
// if(solution==="%"){
// alert(num1 + " % "  +num2 + " = "  + (num1 % num2 ));
// }



// -----------------------------End of Question 11-------------------------

//====================================THE END===================================



