// ASSIGNMENT OF QUESTION: 9 & 10

// --------------------------Question 1---------------------------------
var cityName = prompt("Enter Your City Name");
if (cityName == "Karachi") {
    alert("Welcome to city of lights")
}
else {
    alert("Welcome");
}


// -----------------------------End of Question 1-------------------------

// -----------------------------Question 2---------------------------------

// var gender = prompt("Your gender identity");
// if (gender == Male) {
//     alert("Good Morning Sir");
// }
// else if (gender == Female) {
//     alert("Good Morning Ma’am");
// }
// else { 
//     alert("Good Morning");
// }

// -----------------------------End of Question -------------------------



// -----------------------------Question 5---------------------------------


// -----------------------------Question 8---------------------------------
// var givenNum = prompt("Enter any Number");
// if (givenNum / 3) {
//     alert(givenNum + " is divisible by" + 3);
// }
// else {
//         alert(givenNum + " is not divisible by" + 3)
//     }

// -----------------------------End of Question 8-------------------------



// -----------------------------Question 9---------------------------------
// var num = prompt("Enter a Number");
// if (num / 2) {
//     console.log("Your "+ num + " is even")
// }
// if (num is odd) {
//     console.log("Your "+ num + " is odd")
//     }

// -----------------------------End of Question 9-------------------------

// -----------------------------Question 10---------------------------------
// var temp = prompt("What's temperature in your city");
// if (temp > 40) {
//     document.writeg("It is too hot outside.");
// }
// if (temp >30) {
//     document.writeg("The Weather today is Normal.");
// }
// if (temp >20) {
//     document.writeg("Today’s Weather is cool.");
// }
// if (temp >10) {
//     document.writeg("OMG! Today’s weather is so Cool.");


// -----------------------------End of Question 10-------------------------


// -----------------------------Question 11---------------------------------
// var num1 = prompt("Enter First  Number");
// var num1 = prompt("Enter Second  Number");
// // Addition
// var newNum = num1 + num2 ;
// document.write(newNum);

// // Subtraction
// var newNum = num1 - num2 ;
// document.write(newNum);

// // Multiplication
// var newNum = num1 * num2 ;
// document.write(newNum);

// // Division
// var newNum = num1 / num2 ;
// document.write(newNum);

// // Modulus
// var newNum = num1 % num2 ;
// document.write(newNum);

// -----------------------------End of Question 11-------------------------



