// ASSIGNMENT 3 Variables For Numbers//

//Question 1
//  var age = +15 ;
//  alert("I am " +15 +" years old");
// ------------------------------End of Question 1-----------------------------

//Question 2
// var visit = +5 ;
// alert("You have visited this site " +visit+ " times a day."); 
// ------------------------------End of Question 2-----------------------------

//Question 3
// var birthYear =2020;
// document.write("My birth year is " + birthYear +"<br>");
// document.write("Data type of my declared variable is " + typeof(birthYear));
// -----------------------------End of Question 3------------------------------

//Question 4
// var visitorName = prompt("Enter your Name");
// var productTitle = prompt("Enter the product who you want?");
// var quantity = +prompt( "How much quantity will you buy?");

// document.write(visitorName+ " ordered " + quantity + " " + productTitle  + " on My Online Store." )
// ------------------------------End of Question 4------------------------------
