////ASSIGNMENT START//

//Question no 1
alert("Welcome to our website!\n Miss hina, Miss tayaba, Miss Quaratulein");

//Question no 2
alert("JavaScript Alert\n\n Error! Please enter a valid password.");

//Question no 3
alert("JavaScript Alert\n\nWelcome to JS Land...\nHappy coding!");

//Question no 4
alert("JavaScript Alert\n\n Welcome to JS Land...");
alert("Happy coding!\n Prevent this page is creating for addition dialogs");

//Question no 5
  alert("JavaScript Alert\n\n Hello...I can run Js through my web browser's console");