// Assignment 26-30: Math Method

// ======================Question#1============================

    // let user = prompt("Enter a positive integer");
    // document.write("<h1>Values of Positive integer:</h1>");

    // // Number
    // let num = Number(user);
    // document.write("Number: " + num +"<br>");

    // // Round off Value
    // let roundValue = Math.round(num);
    // document.write("Round off value: " + roundValue +"<br>");

    // // Floor Value
    // let floorValue = Math.floor(num);
    // document.write("Floor Value: "+ floorValue +"<br>");

    // // Ceil Value
    // let ceilValue = Math.ceil(num);
    // document.write("Ceil Value: " + ceilValue +"<br>");
   
// =========================End==============================

// ======================Question#2============================

// let userValue = prompt("Enter a negative integer");
// document.write("<h1>Values of Negative integer:</h1>");

// // Number
// let negNum = Number(userValue);
// document.write("Number: " + negNum +"<br>");

// // Round off Value
// let round_Value = Math.round(negNum);
// document.write("Round off value: " + round_Value +"<br>");

// // Floor Value
// let floor_Value = Math.floor(negNum);
// document.write("Floor Value: "+ floor_Value +"<br>");

// // Ceil Value
// let ceil_Value = Math.ceil(negNum);
// document.write("Ceil Value: " + ceil_Value +"<br>");

// =========================End==============================

// ======================Question#3============================

// let value = Number(prompt("Enter a value"));
// let absValue = Math.abs(value);
// document.write("<h1>Absolute Value:</h1>");
// document.write("The absolute value of " +value +" is " +absValue);

// =========================End==============================

// ======================Question#4============================

var bigDecimal = Math.random();
 var improvedNum = (bigDecimal * 6) + 1;
 var numberOfStars = Math.floor(improvedNum);
// =========================End==============================

// ======================Question#5============================

// =========================End==============================

// ======================Question#6============================

// =========================End===============================

// ======================Question#7============================

// =========================End===============================

// ======================Question#8============================

// =========================End===============================