// Assignment 26-30: Math Method

// ======================Question#1============================

    // let user = prompt("Enter a positive integer");
    // document.write("<h1>Values of Positive integer:</h1>");

    // // Number
    // let num = Number(user);
    // document.write("Number: " + num +"<br>");

    // // Round off Value
    // let roundValue = Math.round(num);
    // document.write("Round off value: " + roundValue +"<br>");

    // // Floor Value
    // let floorValue = Math.floor(num);
    // document.write("Floor Value: "+ floorValue +"<br>");

    // // Ceil Value
    // let ceilValue = Math.ceil(num);
    // document.write("Ceil Value: " + ceilValue +"<br>");
   
// =========================End==============================

// ======================Question#2============================

// let userValue = prompt("Enter a negative integer");
// document.write("<h1>Values of Negative integer:</h1>");

// // Number
// let negNum = Number(userValue);
// document.write("Number: " + negNum +"<br>");

// // Round off Value
// let round_Value = Math.round(negNum);
// document.write("Round off value: " + round_Value +"<br>");

// // Floor Value
// let floor_Value = Math.floor(negNum);
// document.write("Floor Value: "+ floor_Value +"<br>");

// // Ceil Value
// let ceil_Value = Math.ceil(negNum);
// document.write("Ceil Value: " + ceil_Value +"<br>");

// =========================End==============================

// ======================Question#3============================

// let value = Number(prompt("Enter a value"));
// let absValue = Math.abs(value);
// document.write("<h1>Absolute Value:</h1>");
// document.write("The absolute value of " +value +" is " +absValue);

// =========================End==============================

// ======================Question#4============================

// let randomNo = Math.random();
//  let decimal = (randomNo * 6) + 1;
//  let dice = Math.floor(decimal);
//  document.write("<h1>Random Dice Value:</h1>")
//  document.write("random dice value: " + dice);


// =========================End==============================
// 

// ======================Question#5============================

// let coin = Math.floor(Math.random() * 2) + 1;
// document.write("<h1>Random coin value:</h1>")

// if (coin === 1) {
//     document.write(coin + "<br>" + "random coin value: tail")
// }
// else {
//     document.write(coin + "<br>" + "random coin value: head")
// }

// =========================End==============================

// ======================Question#6============================

// let random = Math.floor(Math.random() * 100) +  1;
// document.write("<h1>Random Numbers:</h1>")

// document.write("random num between 1 and 100: " + random);

// =========================End===============================

// ======================Question#7============================

// var Input = prompt("Enter your weight:");

// var weight = parseFloat(Input);

// if (!isNaN(weight)) {
//   document.write("Your weight is: " + weight + " kgs");
// } 
// else {
//   document.write("Invalid weight");
// }

// =========================End===============================

// ======================Question#8============================

// let userNum = +prompt("Enter a number between 1 to 10");
// let secretNo = Math.floor(Math.random() * 10) + 1;

// if (userNum === secretNo) {
//     alert("Congratulations! Your guess number is same as secret number");
// }
// else {
//     alert("Sorry, Your guess value is incorrect \n Try again");
// }

// =========================End===============================