// Assignment: IF...ELSE & ELSE IF STATEMENT,TESTING SET OF CONDITIONS

// ----------------------------Question 1---------------------------------

// var input = prompt("Enter number or alphabet")
// if( input>="0" && input<="9"){
//     alert("Your input is a number ");
// }
// else if(input>="A" && input<="Z" ){
//     alert("Your input is a uppercase letter ");
// }
// else if( input>="a" && input<="z"){
//     alert("Your input is a Lowercase letter ");
// }
// --------------------------End of Question 1----------------------------

// ----------------------------Question 2---------------------------------

// var value1 = prompt("Put Integer 1");
// var value2 = prompt("Put Integer 2");
// if(value1 > value2){
//     document.write(value1 + " is larger than " + value2);
// }
// else if(value1 < value2){
//     document.write(value2 + " is larger than " + value1);
// }
// else{
//     document.write("both number are equal")
// }

// --------------------------End of Question 2----------------------------


// ----------------------------Question 3---------------------------------

// var input = prompt("Enter your Number");
// if(input>0){
//   document.write(input + " is positive num")
// }
// else if (input<0){
//     document.write(input + " is negative num")
// }
// else {
//     document.write("Your value is zero");
// }

// --------------------------End of Question 3----------------------------


// ----------------------------Question 4---------------------------------

// var character =prompt("Enter any alphabet");
// if (character==="a"||character==="e"||character==="i"||character==="o"||character==="u"){
//     alert("True Your alphabet is vowels")
// }
// else {
//     alert("False Your alphabet is not a vowels")
// }


// --------------------------End of Question 4----------------------------


// ----------------------------Question 5---------------------------------

// var password = "12345";
// var userPassword = prompt(" Enter your 5 digit password");
// var empty ="";
// if (userPassword===empty){
//     alert("Please enter your password");
// }
// else if(password===userPassword){
//     alert("Correct! The password you entered matches the original password");
// }
// else {
//     alert("Incorrect Password")
// }


// --------------------------End of Question 5----------------------------


// ----------------------------Question 6---------------------------------
// var greeting;
// var hour = 13;
// if (hour < 18) {
// greeting = "Good day";
////currly bracket is missing that's wht the statment doesn't work
// else ////anothercurrly bracket is missing that's wht the statment doesn't work
// greeting = "Good evening";
// }

//correct statement

// var greeting;
// var hour = 13;
// if (hour < 18) {
// greeting = "Good day";
// }
// else{
// greeting = "Good evening";
// }

// --------------------------End of Question 6----------------------------


// ----------------------------Question 7---------------------------------

// var time = prompt(" Enter time according to 24 hour clock like 0000 to 2400");
// if (time>=0000 && time< 1200){
//     alert("Good Morning");
//     }
// else if (time>=1200 && time< 1700){
//         alert("Good Afternoon");
//         }
// else if (time>=1700 && time< 2100){
//      alert("Good Evening");
//     }
// else if (time>=2100 && time< 2359){
//         alert("Good Night");
//        }
// else {
//     alert("Your time is incorrect");
// }
// --------------------------End of Question 7----------------------------