// Assginment # 43-48: EVENTS.

// ================================Question1==============================

//  function popup(message) {
//      alert(message);
//      }

// ==================================End==================================

// ================================Question2==============================

// function greetTheUserimg1(){
//     alert("Thanks for purchansing oppo from us")
// }
// function greetTheUserimg2(){
//     alert("Thanks for purchansing iphone from us")
// }
// function greetTheUserimg3(){
//     alert("Thanks for purchansing samsung from us")
// }
// function greetTheUserimg4(){
//     alert("Thanks for purchansing iphone from us")
// }

// ==================================End==================================

// ================================Question3==============================

// function deleteRow(r) {
//     var i = r.parentNode.parentNode.rowIndex;
//     document.getElementById("myTable").deleteRow(i);
//   }

// ==================================End==================================


// ================================Question4==============================

//code in index.html

// ==================================End==================================


// ================================Question5==============================

// let counter = 0;

// function increment() {
//   counter++;
//   document.getElementById('counter').textContent = counter;
// }

// function decrement() {
//   if (counter > 0) {
//     counter--;
//     document.getElementById('counter').textContent = counter;
//   }
// }

// ==================================End=================================